travis:
  secure:
    BINSTAR_TOKEN: qd/RuVwFN55ov8bsf0hKmuRWEMBHMc60qN5I0zLLLt+8Q9RPVWRBrt7o6q8c8YIOc8zftY5eHfZRd1cCi+NM67zNyWHAySBPpDClZnKr3dqo9hkREjk11u8isAsyIUPz/9cGd8GMuHWS68Mx/+SSS9OEJCjgbF1NWfhwpGCyFrTDrtux9rOWsIwSXqcByPOupfI+ewl2ed/MhkoRxc4eEwcwRPkeJxjlOIE5iVEOzYX4QD2tGl1V6nfbhRBGrTzVn1hen0+sC0n2C9hrDt0Tnu76bpiqYJCCY6jf+mp64977ZFcafdKL1j0MmxgdIpZ31QsRSSTqI1BRTA3ozHjxVLIgScwOfmi1xzOpJZrGMuX8IhuYip6+P7yC//zni3xXwjaCRlyxkS5zv7oXtm7qqDiV49Qj0AoqwHD2zFCtA2Ij+CmcHX+fh+lUfhWAlus46/f5UVq8nHINCE98g9UWrgLVF36BOVBbYbc/kocCy6KadJ1szKJyYU5dRG/MbkgEB8DsHdfIzJsC1nluuBoLY/kVoGPQG0CdoP9rQjaEx3WbVZ6XutjFyGNXTdayx+yY/asVauImcexTqoDATKCZ+xexXMiJXyyz87eZa0XBGFYR/FWkZJFNmNy/G71ZC15z6cpUhQp0WXjMqcjzan5doAxYuCwFoScqTe2zOmISs+E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
